server {
    listen          0.0.0.0:1025;
    server_name     _;
    root          /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www;
    index           index.html;
    client_max_body_size  2M;

    error_page 400 /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www/errors/error400.html;
    error_page 403 /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www/errors/error403.html;
    error_page 404 /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www/errors/error404_default.html;
    error_page 405 /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www/errors/error405.html;
    error_page 500 /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www/errors/error500.html;

    location /errors/ {
        root /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www;
		proxy_pass http://localhost:5000
    }

    location /test/ {
        autoindex off;
        error_page_sd 400 /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www/errors/error.html;
        error_page_sd 404 /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www/errors/error404.html;
        error_page_sd 405 /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www/errors/error405.html;
        root /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www;
        limit_except GET HEAD {
            deny all;
        }
    }

    location /uploads/ {
       root /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www;
        autoindex on;
    }

    location /upload/ {
        limit_except POST DELETE GET
        upload_store      /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www/uploads;
        root              /Users/nmagdano/Documents/05_rank/01_webserv/new_repo/project/www;
        autoindex          on;
        client_max_body_size  2M
    }

    location /cgi-bin/ {
        cgi_pass    .py;
        root        /usr/local/cgi-bin;
        limit_except GET POST { deny all; }
    }
}
server {
    listen          0.0.0.0:8080;
    server_name     example.com www.example.com;
    root            /home/twillian/srv/example/site;
    index           index.html;
    client_max_body_size 5M;

    location /old/ {
        return 301 /new/;
    }

    location /files/ {
        autoindex on;
    }

    location /tmp/ {
        root /home/twillian/srv/example/;
        limit_except GET DELETE { deny all; }
    }
}